install: true
script:
  - mvn -s .travis-settings.xml -B -fae -DSECMGR=$SECURITY_MGR -P$SERVER_VERSION integration-test

language: java
jdk:
  - oraclejdk9
env:
  - SERVER_VERSION=wildfly1010 SECURITY_MGR=false
  - SERVER_VERSION=wildfly1000 SECURITY_MGR=false
  - SERVER_VERSION=wildfly1100 SECURITY_MGR=false
  - SERVER_VERSION=wildfly1100,secmgr SECURITY_MGR=true
matrix:
  exclude:
    - jdk: oraclejdk9
      env: SERVER_VERSION=wildfly1010 SECURITY_MGR=false
    - jdk: oraclejdk9
      env: SERVER_VERSION=wildfly1000 SECURITY_MGR=false
cache:
 directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
